// Generated by Haxe 4.0.5
import './styles/index.css';
import './styles/App.css';

/* eslint-disable */

;(function ($hx_exports, $global) { "use strict";
var React_Component = require("react").Component;
class App extends React_Component {
	constructor() {
		super();
	}
	render() {
		var logo = require("./assets/logo.svg");
		return { $$typeof : $$tre, type : "div", props : { className : "App", children : { $$typeof : $$tre, type : "header", props : { className : "App-header", children : [{ $$typeof : $$tre, type : "img", props : { src : logo, className : "App-logo", alt : "logo"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : ["Edit ",{ $$typeof : $$tre, type : "code", props : { children : "src/App.hx"}, key : null, ref : null}," and save to reload."]}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null};
	}
	static main() {
		ReactDOM.render(React.createElement(App),window.document.getElementById("root"));
		console.log("App.hx:19:","Application loaded.");
	}
}
$hx_exports["App"] = App;
var React = require("react");
var ReactDOM = require("react-dom");
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
App.displayName = "App";
App.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, {});
